package ma.lias.controller;

import ma.lias.dto.DecisionRequest;
import ma.lias.entity.*;
import ma.lias.repository.*;
import ma.lias.service.*;
import org.springframework.http.*;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDateTime;
import java.util.*;

@RestController @RequestMapping("/api/membership-requests")
public class MembershipRequestController {
  private final MembershipRequestRepository repo; private final UserRepository users; private final MemberRepository members; private final FileStorageService storage; private final EmailService email; private final PasswordEncoder encoder; private final AuditService audit; private final NotificationRepository notifications; private final MemberLifecycleService lifecycle; private final ActiveMandateService activeMandates;
  public MembershipRequestController(MembershipRequestRepository repo, UserRepository users, MemberRepository members, FileStorageService storage, EmailService email, PasswordEncoder encoder, AuditService audit, NotificationRepository notifications, MemberLifecycleService lifecycle, ActiveMandateService activeMandates){this.repo=repo;this.users=users;this.members=members;this.storage=storage;this.email=email;this.encoder=encoder;this.audit=audit;this.notifications=notifications;this.lifecycle=lifecycle;this.activeMandates=activeMandates;}
  @PostMapping("/public") public ResponseEntity<MembershipRequest> submit(@RequestParam String applicantName, @RequestParam String emailAddress, @RequestParam String motivation, @RequestParam(required=false) MultipartFile cv, @RequestParam(required=false) MemberType requestedType, @RequestParam(required=false) String establishment, @RequestParam(required=false) String originLab, @RequestParam(required=false) String interests, @RequestParam(required=false) String biography, @RequestParam(required=false) Long preferredTeamId, @RequestParam(required=false) String phone) throws Exception { String normalized=emailAddress==null?"":emailAddress.trim().toLowerCase(Locale.ROOT); if(users.findByEmail(normalized).isPresent() || repo.findByEmail(normalized).stream().anyMatch(r -> r.getStatus()==MembershipRequestStatus.PENDING)) throw new ResponseStatusException(HttpStatus.CONFLICT,"Une demande ou un compte actif existe déjà pour cet email."); MembershipRequest r=new MembershipRequest(); r.setApplicantName(applicantName); r.setEmail(normalized); r.setMotivation(motivation); r.setRequestedType(requestedType); r.setEstablishment(establishment); r.setOriginLab(originLab); r.setInterests(interests); r.setBiography(biography); r.setPreferredTeamId(preferredTeamId); r.setPhone(phone); if(cv!=null) r.setCvUrl(storage.save(cv,"cv")); MembershipRequest saved=repo.save(r); email.send(normalized,"Demande d'adhésion reçue","Votre demande d'adhésion LIAS a été reçue."); audit.log("CREATE","MembershipRequest",saved.getId(),"Demande publique"); return ResponseEntity.status(HttpStatus.CREATED).body(saved); }
  @GetMapping @PreAuthorize("hasAnyRole('DIRECTOR','ADMIN')") public List<MembershipRequest> all(){ return repo.findAll(); }
  @GetMapping("/{id}") @PreAuthorize("hasAnyRole('DIRECTOR','ADMIN')") public MembershipRequest one(@PathVariable Long id){ return repo.findById(id).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,"Demande introuvable")); }
  @PostMapping("/{id}/decision") @PreAuthorize("hasAnyRole('DIRECTOR','ADMIN')") public MembershipRequest decision(@PathVariable Long id, @RequestBody DecisionRequest decision, org.springframework.security.core.Authentication auth){ MembershipRequest r=one(id); if(r.getStatus()!=MembershipRequestStatus.PENDING) throw new ResponseStatusException(HttpStatus.CONFLICT,"Cette demande a déjà été traitée."); User actor=(User)auth.getPrincipal(); activeMandates.requireActiveDirector(actor); r.setReviewedBy(actor.getId()); r.setReviewedAt(LocalDateTime.now()); r.setDecisionReason(decision.reason()); if(decision.accepted()){ if(users.findByEmail(r.getEmail()).isPresent()) throw new ResponseStatusException(HttpStatus.CONFLICT,"Un compte existe déjà pour cet email."); MemberType memberType=decision.memberType()!=null?decision.memberType():(r.getRequestedType()!=null?r.getRequestedType():MemberType.DOCTORAL); AppRole appRole=decision.appRole()!=null?decision.appRole():defaultRole(memberType); r.setStatus(MembershipRequestStatus.ACCEPTED); String temp=UUID.randomUUID().toString().replace("-","").substring(0,18)+"!aA1"; User u=new User(); u.setEmail(r.getEmail()); u.setPasswordHash(encoder.encode(temp)); u.setAppRole(appRole); users.save(u); Member m=new Member(); m.setUserId(u.getId()); String[] parts=r.getApplicantName().split(" ",2); m.setFirstName(parts[0]); m.setLastName(parts.length>1?parts[1]:""); m.setType(memberType); m.setEstablishment(r.getEstablishment()); m.setOriginLab(r.getOriginLab()); m.setInterests(r.getInterests()); m.setBiography(r.getBiography()); m.setCurrentTeamId(r.getPreferredTeamId()); members.save(m); lifecycle.openInitialAffiliation(m); notifyUser(u.getId(),"Votre adhésion LIAS a été acceptée.","MEMBERSHIP"); email.send(r.getEmail(),"Adhésion acceptée","Votre compte LIAS est créé. Un mot de passe temporaire de première connexion vous a été généré : "+temp); } else { r.setStatus(MembershipRequestStatus.REJECTED); email.send(r.getEmail(),"Adhésion refusée", decision.reason()==null?"Votre demande n'a pas été retenue.":decision.reason()); } audit.log("DECISION","MembershipRequest",id,"Décision: "+r.getStatus()+" par "+actor.getEmail()+" (mandat actif contrôlé)"); return repo.save(r); }
  private AppRole defaultRole(MemberType memberType){ return switch(memberType){ case PERMANENT -> AppRole.PERMANENT_MEMBER; case ASSOCIATE -> AppRole.ASSOCIATE_MEMBER; case DOCTORAL -> AppRole.DOCTORAL; case RETIRED -> AppRole.RETIRED; case FORMER -> AppRole.FORMER; }; }
  private void notifyUser(Long userId,String message,String type){ Notification n=new Notification(); n.setUserId(userId); n.setMessage(message); n.setType(type); notifications.save(n); }
}
