CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, email VARCHAR(255) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE', app_role VARCHAR(80) NOT NULL DEFAULT 'PERMANENT_MEMBER', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS teams (id BIGSERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, description TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS members (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id), first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, photo_url VARCHAR(1000), birth_date DATE, hire_date DATE, biography TEXT, interests TEXT, establishment VARCHAR(255), origin_lab VARCHAR(255), current_team_id BIGINT REFERENCES teams(id), type VARCHAR(80) NOT NULL DEFAULT 'PERMANENT');
CREATE TABLE IF NOT EXISTS affiliations (id BIGSERIAL PRIMARY KEY, member_id BIGINT REFERENCES members(id), lab_id BIGINT, start_date DATE, end_date DATE);
CREATE TABLE IF NOT EXISTS mandates (id BIGSERIAL PRIMARY KEY, director_id BIGINT REFERENCES members(id), vice_director_id BIGINT REFERENCES members(id), start_date DATE, end_date DATE);
CREATE TABLE IF NOT EXISTS team_chiefs (id BIGSERIAL PRIMARY KEY, mandate_id BIGINT REFERENCES mandates(id), member_id BIGINT REFERENCES members(id), team_id BIGINT REFERENCES teams(id), start_date DATE, end_date DATE);
CREATE TABLE IF NOT EXISTS roles_history (id BIGSERIAL PRIMARY KEY, member_id BIGINT REFERENCES members(id), role VARCHAR(80), start_date DATE, end_date DATE);
CREATE TABLE IF NOT EXISTS membership_requests (id BIGSERIAL PRIMARY KEY, applicant_name VARCHAR(255), email VARCHAR(255), cv_url VARCHAR(1000), motivation TEXT, status VARCHAR(80) DEFAULT 'PENDING', reviewed_by BIGINT REFERENCES users(id), reviewed_at TIMESTAMP, decision_reason TEXT);
CREATE TABLE IF NOT EXISTS events (id BIGSERIAL PRIMARY KEY, title VARCHAR(255), type VARCHAR(80), description TEXT, start_date TIMESTAMP, end_date TIMESTAMP, location VARCHAR(255), organizer_id BIGINT, edition VARCHAR(120), archived BOOLEAN DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS event_participants (id BIGSERIAL PRIMARY KEY, event_id BIGINT REFERENCES events(id), member_id BIGINT REFERENCES members(id));
CREATE TABLE IF NOT EXISTS publications (id BIGSERIAL PRIMARY KEY, title VARCHAR(255), abstract_text TEXT, authors TEXT, year INT, team_id BIGINT REFERENCES teams(id), added_by BIGINT REFERENCES members(id), doi VARCHAR(255), publication_url VARCHAR(1000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents (id BIGSERIAL PRIMARY KEY, event_id BIGINT REFERENCES events(id), type VARCHAR(80), file_url VARCHAR(1000), filename VARCHAR(255), uploaded_by BIGINT REFERENCES users(id), uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS material_inventory (id BIGSERIAL PRIMARY KEY, name VARCHAR(255), description TEXT, quantity INT DEFAULT 0, received_at DATE, supplier VARCHAR(255));
CREATE TABLE IF NOT EXISTS material_distributions (id BIGSERIAL PRIMARY KEY, material_id BIGINT REFERENCES material_inventory(id), member_id BIGINT REFERENCES members(id), quantity INT DEFAULT 1, distributed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, distributed_by BIGINT REFERENCES members(id));
CREATE TABLE IF NOT EXISTS material_requests (id BIGSERIAL PRIMARY KEY, requested_by BIGINT REFERENCES users(id), material_name VARCHAR(255), quantity INT DEFAULT 1, justification TEXT, status VARCHAR(80) DEFAULT 'PENDING', reviewed_by BIGINT REFERENCES users(id), reviewed_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS meetings (id BIGSERIAL PRIMARY KEY, title VARCHAR(255), date TIMESTAMP, agenda TEXT, pv_url VARCHAR(1000), created_by BIGINT REFERENCES members(id));
CREATE TABLE IF NOT EXISTS messages (id BIGSERIAL PRIMARY KEY, sender_id BIGINT REFERENCES users(id), team_id BIGINT REFERENCES teams(id), event_id BIGINT REFERENCES events(id), content TEXT, sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, is_global BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS notifications (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id), message TEXT, type VARCHAR(120), is_read BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS conventions (id BIGSERIAL PRIMARY KEY, partner_name VARCHAR(255), partner_country VARCHAR(120), start_date DATE, end_date DATE, description TEXT, document_url VARCHAR(1000));
CREATE TABLE IF NOT EXISTS annual_reports (id BIGSERIAL PRIMARY KEY, year INT NOT NULL, generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, file_url VARCHAR(1000), generated_by BIGINT REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_log (id BIGSERIAL PRIMARY KEY, actor_id BIGINT REFERENCES users(id), action VARCHAR(120), entity_type VARCHAR(120), entity_id BIGINT, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, details TEXT);
CREATE TABLE IF NOT EXISTS system_settings (id BIGSERIAL PRIMARY KEY, setting_key VARCHAR(255) UNIQUE, setting_value TEXT);
CREATE INDEX IF NOT EXISTS idx_members_team ON members(current_team_id);
CREATE INDEX IF NOT EXISTS idx_publications_year ON publications(year);
CREATE INDEX IF NOT EXISTS idx_events_start_date ON events(start_date);
CREATE INDEX IF NOT EXISTS idx_documents_type ON documents(type);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_log(timestamp);
