ALTER TABLE documents ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS archived_at TIMESTAMP;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE material_requests ADD COLUMN IF NOT EXISTS review_reason TEXT;
